### ISSUE TITLE
Composite product sign up fee miscalculated

### ISSUE THREAD

**Issue by RobMaple** [seb86/woocommerce-subscribe-to-all-the-things-signup-trial-add-on#5]
Appreciate this plugin is still in development but I found it after half integrating the same functionality myself so am giving it a go as a replacement.

It seems to be working ok generally although I've noticed that when used on composite products with a sign-up fee specified, this gets miscalculated at the cart / checkout. 
It seems the issue is stemming from the **update_cart_item_sub_data** function being called for each of the child products as well as the parent and results in the signup fee being applied multiple times depending on the total products the component product comprises of.

As a fix I've wrapped the internals of this function with a check to make sure the cart item it's being called on doesn't have a parent. This works fine for my use case but I don't know if this is necessarily the best way to do this.

**Comment by seb86** [comment]
@RobMaple When you are ready to share I look forward to testing your changes. Please push them to the _issue-5_ branch. Thank you.

**Comment by seb86** [comment]
@RobMaple I have applied significant changes to the structure of the plugin.

**Comment by seb86** [comment]
> This works fine for my use case but I don't know if this is necessarily the best way to do this.

@RobMaple If you push your fix I can the see if it is the best way.

**Comment by seb86** [comment]
@RobMaple Can you create a pull request into the "issue-5" branch, please. Thank you.

**Comment by seb86** [comment]
@RobMaple Thank you for your commit. I have made it more viable for all bundle product types with commit af3d3ce384ec6029fe81c4d6f72c09c6357af3c9. I am now merging it with the master.
